source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Ruby version
ruby '2.4.1'
# PDF parser
gem 'pdf-reader', '~> 1.4'
# Debugging
gem 'pry', '~> 0.10.3'
# Colorized Output
gem 'colorize', '~> 0.8.1'
