source 'https://rubygems.org'
# Ruby version
ruby '2.4.1'
# PDF parser
gem 'pdf-reader', '~> 1.4'
# Debugging
gem 'pry', '~> 0.10.3'
# Colorized Output
gem 'colorize', '~> 0.8.1'
# BETTER PDF parser
gem 'yomu'
# PDF generator
gem 'hexapdf', '~> 0.7.0'
